// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var EditorPanelView, editorPanel_tpl;
    editorPanel_tpl = require('hbs!./edit-handler-panel');
    return EditorPanelView = Backbone.View.extend({
      tagName: 'div',
      className: 'audio-handler',
      initialize: function() {
        this.$el.draggable({
          containment: 'parent',
          axis: "x"
        });
        return this.$el.resizable({
          containment: "parent",
          handles: "e, w"
        });
      }
    });
  });

}).call(this);
