// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var wavePanel, wavesurfer;
    wavePanel = require('hbs!wave-panel');
    wavesurfer = require('wavesurfer/wavesurfer');
    $('body').append(wavePanel());
    $('#file').on('change', function() {
      var file;
      file = $(this).prop('files')[0];
      return wavesurfer.loadFile(file);
    });
    wavesurfer.init({
      canvas: document.querySelector("#wave"),
      cursor: document.querySelector("#wave-cursor"),
      color: "#99CC00"
    });
    return wavesurfer.bindDragNDrop();
  });

}).call(this);
