// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var EditorPanelView, wavePanel, wavesurfer;
    wavePanel = require('hbs!./wave-panel');
    wavesurfer = require('./wavesurfer/wavesurfer');
    EditorPanelView = require('./edit-handler');
    $('body').append(wavePanel());
    $('#file').on('change', function() {
      var editorPanelView, file;
      file = $(this).prop('files')[0];
      wavesurfer.loadFile(file);
      editorPanelView = new EditorPanelView({
        container: $('.audio-editor')
      });
      return $('.audio-editor').append(editorPanelView.$el);
    });
    return wavesurfer.init({
      canvas: document.querySelector("#wave"),
      width: 1024,
      height: 256,
      cursor: document.querySelector("#wave-cursor"),
      color: "#99CC00"
    });
  });

}).call(this);
