// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var WavePanelView;
    WavePanelView = require('./wave-panel-view');
    $('#file').on('change', function() {
      var file, wavePanelView;
      $('.audio-editor').remove();
      wavePanelView = new WavePanelView({
        width: 1024,
        height: 256,
        color: '#99CC00'
      });
      $('#wave_container').append(wavePanelView.$el);
      file = $(this).prop('files')[0];
      return wavePanelView.loadFile(file);
      /*
          $('#export').click(()->
            wavesurfer.export()
          )
      */

    });
    return $('#choose').on('click', function() {
      return $('#file').trigger('click');
    });
  });

}).call(this);
