// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var WavePanelView, wavesurfer;
    wavesurfer = require('./lib/wave/wavesurfer');
    WavePanelView = require('./wave-panel-view');
    $('#file').on('change', function() {
      var file, wavePanelView;
      $('.audio-editor').remove();
      wavePanelView = new WavePanelView();
      $('#wave_container').append(wavePanelView.$el);
      wavesurfer.init({
        canvas: document.querySelector("#wave"),
        width: 1024,
        height: 256,
        cursor: document.querySelector("#wave-cursor"),
        color: "#99CC00"
      });
      file = $(this).prop('files')[0];
      wavesurfer.loadFile(file);
      return $('#export').click(function() {
        return wavesurfer["export"]();
      });
    });
    return $('#choose').on('click', function() {
      return $('#file').trigger('click');
    });
  });

}).call(this);
