// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Drawer, WaveSurfer, WebAudio, exports;
    WebAudio = require('./webaudio');
    Drawer = require('./drawer');
    WaveSurfer = {
      init: function(params) {
        var _this = this;
        this.webAudio = new WebAudio(params);
        this.drawer = Drawer;
        this.drawer.init(params);
        return this.webAudio.proc.onaudioprocess = function() {
          return _this.onAudioProcess();
        };
        /*
              @drawer.bindClick (percents)=>
                @playAt percents
        */

      },
      events: {},
      bind: function(type, callback) {
        if (!(this.events[type] != null)) {
          this.events[type] = $.Callbacks();
        }
        return this.events[type].add(callback);
      },
      trigger: function(type, opts) {
        if (this.events[type] != null) {
          return this.events[type].fire(opts);
        }
      },
      onAudioProcess: function() {
        if (!this.webAudio.paused) {
          this.updatePercents();
          if (this.currentPercents < 1) {
            return this.trigger('playing', this.currentPercents);
          }
        }
      },
      updatePercents: function() {
        var d, percents;
        d = this.webAudio.ac.currentTime - this.webAudio.lastPlay;
        percents = d / this.webAudio.getDuration();
        return this.currentPercents = this.lastPlayPercents + percents;
      },
      playAt: function(percents) {
        this.webAudio.play(this.webAudio.getDuration() * percents);
        return this.lastPlayPercents = percents;
      },
      pause: function() {
        this.webAudio.pause();
        return this.updatePercents();
      },
      playPause: function() {
        if (this.webAudio.paused) {
          return this.playAt(this.currentPercents || 0);
        } else {
          return this.pause();
        }
      },
      setSelection: function(from, to) {
        return this.webAudio.setSelection(from, to);
      },
      getSelection: function() {
        return this.webaudio.getSlection();
      },
      getFileName: function() {
        return this._fileName;
      },
      "export": function() {
        return this.webAudio["export"]();
      },
      draw: function() {
        return this.drawer.drawBuffer(this.webAudio.currentBufferData);
      },
      load: function(src) {
        var self, xhr;
        self = this;
        xhr = new XMLHttpRequest();
        xhr.responseType = "arraybuffer";
        xhr.onload = function() {
          return self.webAudio.loadData(xhr.response, self.draw.bind(self));
        };
        xhr.open("GET", src, true);
        return xhr.send();
      },
      loadFile: function(file) {
        var reader, _dfr,
          _this = this;
        this._fileName = file.name;
        _dfr = $.Deferred();
        reader = new FileReader();
        reader.addEventListener("load", function(e) {
          var loadData_dfr;
          loadData_dfr = _this.webAudio.loadData(e.target.result, _this.draw.bind(_this));
          return loadData_dfr.done(function() {
            return _dfr.resolve();
          });
        }, false);
        reader.readAsArrayBuffer(file);
        return _dfr;
      },
      bindDragNDrop: function(dropTarget) {
        var reader, self;
        self = this;
        reader = new FileReader();
        reader.addEventListener("load", (function(e) {
          return self.webAudio.loadData(e.target.result, self.draw.bind(self));
        }), false);
        return (dropTarget || document).addEventListener("drop", (function(e) {
          var file;
          e.preventDefault();
          file = e.dataTransfer.files[0];
          return file && reader.readAsArrayBuffer(file);
        }), false);
      },
      destroy: function() {
        delete this.drawer;
        this.webAudio.destroy();
        delete this.webAudio;
        return console.log('destroy');
      }
    };
    return exports = WaveSurfer;
  });

}).call(this);
